version: '3.7'
services:
  # Webアプリ
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./sample:/var/www/html
  # DBサービス
  db:
    image: mysql:8.0.17
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=sample
      - TZ='Asia/Tokyo'
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - data:/var/lib/mysql

  # Adminerサービス
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  data:
