version: '3.7'
services:
  # DBサービス
  db:
    image: mysql:8.0.17
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=sample
      - TZ='Asia/Tokyo'
    ports:
      - 3306:3306

  # Adminerサービス
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
